apiVersion: v1
kind: ServiceAccount
metadata:
  name: nfproxy
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: nfproxy
rules:
- apiGroups:
  - ""
  resources:
  - endpoints
  - services
  verbs:
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
  - update
- apiGroups:
  - events.k8s.io
  resources:
  - events
  verbs:
  - create
- apiGroups:
  - events.k8s.io
  resources:
  - events
  verbs:
  - patch
- apiGroups:
  - events.k8s.io
  resources:
  - events
  verbs:
  - update
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - list
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: nfproxy
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: nfproxy
subjects:
- kind: ServiceAccount
  name: nfproxy
  namespace: kube-system
---
apiVersion: apps/v1
kind: DaemonSet
spec:
  selector:
    matchLabels:
      app: nfproxy
  template:
    metadata:
      labels:
        app: nfproxy
    spec:
      serviceAccountName: nfproxy
      hostNetwork: true
      containers:
        - name: nfproxy
          image: docker.io/sbezverk/nfproxy:0.0.0
          imagePullPolicy: Always
          securityContext:
            privileged: true
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          args:
            - --ipv4clustercidr
            - "57.112.0.0/12"
            - --ipv6clustercidr
            - ""
          env:
            - name: NFPROXY_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
metadata:
  name: nfproxy
  namespace: kube-system
